spring:
    application:
        name: ProjectTask
    profile:
        active: prod
    jackson:
        serialization:
            fail-on-empty-beans: false
server:
    servlet:
        context-path: /projectTasks/v1
    port: 9082
